name: taskflow
description: A Flutter app for managing tasks and routines.

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  fl_chart:
    git:
      url: https://github.com/imaNNeoFighT/fl_chart.git
  uuid: ^4.5.0
  timezone: ^0.9.4
  syncfusion_flutter_charts: ^27.1.48

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true